import { NgModule } from '@angular/core';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { CdkTableModule } from '@angular/cdk/table'; 
import {
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    MatDialogModule,
    MatSidenavModule,
    MatExpansionModule,
    MatMenuModule,
    MatListModule,
    MatRippleModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatSlideToggleModule,
    MatDividerModule,
    MatTabsModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatGridListModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatChipsModule
 } from '@angular/material';

@NgModule({
    imports: [
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatButtonModule,
        MatToolbarModule,
        MatIconModule,
        MatDialogModule,
        MatSidenavModule,
        MatExpansionModule,
        MatMenuModule,
        MatListModule,
        MatRippleModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatSlideToggleModule,
        MatDividerModule,
        MatTabsModule,
        DragDropModule,
        ScrollingModule,
        CdkTableModule,
        DragDropModule,
        MatButtonToggleModule,
        MatProgressSpinnerModule,
        MatGridListModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatChipsModule
    ],
    exports: [
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatButtonModule,
        MatToolbarModule,
        MatIconModule,
        MatDialogModule,
        MatSidenavModule,
        MatExpansionModule,
        MatMenuModule,
        MatListModule,
        MatRippleModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatSlideToggleModule,
        MatDividerModule,
        MatTabsModule,
        DragDropModule,
        ScrollingModule,
        CdkTableModule,
        DragDropModule,
        MatButtonToggleModule,
        MatProgressSpinnerModule,
        MatGridListModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatChipsModule
    ]
})

export class MaterialModule {}